// Builds core/ for wasm32 and writes it into the bundle as base64:
//
//   node scripts/build-wasm.mjs [--check]
//
// src/tzx/core.wasm.ts is generated, not tracked. Base64 rather than an asset
// import because the same module has to load in the browser and in vitest under
// node, and because inlining it costs one less round trip at startup.
//
// The wasm target needs a rustup toolchain: Homebrew's rust only ships the host
// standard library. Set CARGO to override which cargo is used.
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const CRATE = path.resolve('core');
const WASM = path.join(CRATE, 'target/wasm32-unknown-unknown/release/tapeti_core.wasm');
const OUT = path.resolve('src/tzx/core.wasm.ts');

function findCargo() {
  if (process.env.CARGO) return process.env.CARGO;
  // rustup's shim knows about the wasm32 target; a Homebrew cargo does not.
  const rustup = path.join(os.homedir(), '.cargo/bin/cargo');
  return fs.existsSync(rustup) ? rustup : 'cargo';
}

try {
  execFileSync(findCargo(), ['build', '--release', '--target', 'wasm32-unknown-unknown'], {
    cwd: CRATE,
    stdio: ['ignore', 'ignore', 'pipe'],
    encoding: 'utf8',
  });
} catch (e) {
  const err = String(e.stderr || e.message);
  process.stderr.write(err);
  if (/can't find crate for `std`|target may not be installed/.test(err)) {
    process.stderr.write('\nThe wasm32 target is missing: rustup target add wasm32-unknown-unknown\n');
  }
  process.exit(1);
}

const bytes = fs.readFileSync(WASM);
const body = `// Generated by scripts/build-wasm.mjs from core/. Do not edit.\n`
  + `// ${bytes.length} bytes of wasm, base64 encoded.\n`
  + `export const CORE_WASM_BASE64 =\n  '${bytes.toString('base64')}';\n`;

const unchanged = fs.existsSync(OUT) && fs.readFileSync(OUT, 'utf8') === body;
if (process.argv.includes('--check')) {
  if (!unchanged) {
    process.stderr.write('src/tzx/core.wasm.ts is out of date; run npm run core:wasm\n');
    process.exit(1);
  }
} else if (!unchanged) {
  // Only write on a change, so vite does not reload for an identical build.
  fs.writeFileSync(OUT, body);
}
console.log(`core.wasm: ${bytes.length} bytes (${Math.round((bytes.length * 4) / 3 / 1024)} KB as base64)${unchanged ? ', unchanged' : ''}`);
